# SPDX-License-Identifier: GPL-2.0
#
# Cisco 2811 (relicnos) board support
#

obj-y := setup.o irq.o time.o serial.o mv64340_irq.o eth.o
obj-$(CONFIG_CISCO2811_PATA)	+= pata.o
obj-$(CONFIG_PCI)		+= pci.o
obj-$(CONFIG_CISCO2811_NM32A)	+= nm32a.o
