#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Turn an extracted cd2481_ucode.bin into the header the driver compiles in.

Kept separate from the extractor so the licence-sensitive step (pulling Cisco
firmware out of an image you own) stays distinct from the mechanical one.

    ./extract_cd2481_ucode.py <ios-image> -o cd2481_ucode.bin
    ./gen_ucode_header.py cd2481_ucode.bin -o kernel/cisco2811/cd2481_ucode.h
"""
import argparse

ap = argparse.ArgumentParser()
ap.add_argument('blob')
ap.add_argument('-o', '--out', default='cd2481_ucode.h')
a = ap.parse_args()

d = open(a.blob, 'rb').read()
if len(d) != 18432:
    raise SystemExit(f'expected 18432 bytes, got {len(d)}')

with open(a.out, 'w') as f:
    f.write('/* SPDX-License-Identifier: GPL-2.0 */\n')
    f.write('/*\n * CD2481 microcode, generated by tools/gen_ucode_header.py.\n')
    f.write(' *\n * NOT redistributable: this is Cisco firmware extracted from an IOS image.\n')
    f.write(' * Regenerate it locally, do not commit it.\n */\n')
    f.write('#ifndef _CD2481_UCODE_H\n#define _CD2481_UCODE_H\n\n')
    f.write('#define CD2481_UCODE_INSNS\t8192\n\n')
    f.write(f'static const unsigned char cd2481_ucode[{len(d)}] = {{\n')
    for i in range(0, len(d), 12):
        f.write('\t' + ', '.join(f'0x{b:02x}' for b in d[i:i+12]) + ',\n')
    f.write('};\n\n#endif\n')
print(f'wrote {a.out} ({len(d)} bytes)')
